# Generated by Django 3.1 on 2020-11-28 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomodation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='accomodation_id',
            new_name='accomodation',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='tarif_accomodation',
            old_name='accomodation_id',
            new_name='accomodation',
        ),
        migrations.RenameField(
            model_name='tarif_accomodation',
            old_name='tarif_id',
            new_name='tarif',
        ),
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 5, 28)),
        ),
    ]
