# Generated by Django 3.1 on 2020-11-28 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20201128_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='id',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='Incorrect length', message='Length has to be 8', regex='^\\d{8}$')]),
        ),
    ]
