# Generated by Django 3.1 on 2020-11-28 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20201128_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_activ',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_date_of_prolongation',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 5, 28), null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
