# Generated by Django 3.1 on 2020-11-28 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20201129_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_date_of_prolongation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
