# Generated by Django 3.1 on 2020-11-28 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_auto_20201129_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='last_date_of_prolongation',
            field=models.DateField(default=datetime.date(2020, 11, 29)),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
