# Generated by Django 3.1 on 2020-11-28 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodation',
            name='user',
        ),
    ]
