# Generated by Django 3.1 on 2020-11-29 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_remove_accomodation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='last_date_of_prolongation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='pay_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 1, 40, 32152), editable=False),
        ),
    ]
