# Generated by Django 3.1 on 2020-11-29 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_auto_20201129_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 25, 29, 53981), editable=False),
        ),
    ]
