# Generated by Django 3.1 on 2020-11-30 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0012_auto_20201129_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 5, 30)),
        ),
    ]
