# Generated by Django 3.1 on 2020-12-04 02:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0013_auto_20201130_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.status')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.tarif')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_activ',
        ),
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 6, 4)),
        ),
        migrations.DeleteModel(
            name='Tarif_Accomodation',
        ),
        migrations.AlterField(
            model_name='tarif',
            name='accomodation',
            field=models.ManyToManyField(through='homePage.Tarif_Status', to='homePage.Status'),
        ),
    ]
