# Generated by Django 3.1 on 2020-12-11 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_auto_20201204_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 6, 11)),
        ),
    ]
