# Generated by Django 3.1 on 2020-12-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0016_auto_20201212_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
