# Generated by Django 3.1 on 2020-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0018_auto_20201212_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_activ',
            field=models.BooleanField(default=True),
        ),
    ]
