# Generated by Django 3.1 on 2021-01-04 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0021_auto_20210102_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 7, 4)),
        ),
    ]
