# Generated by Django 3.1 on 2021-01-06 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0022_auto_20210104_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 7, 6)),
        ),
        migrations.AlterField(
            model_name='status',
            name='accomodation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.accomodation'),
        ),
    ]
