# Generated by Django 3.1 on 2021-01-07 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0023_auto_20210106_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='term',
            field=models.DateField(default=datetime.date(2021, 7, 7)),
        ),
        migrations.AlterField(
            model_name='status',
            name='date_in',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 18, 59, 48, 673380)),
        ),
    ]
